### ISSUE TITLE
Não está atualizando lista de imagens ao se realizar múltiplas buscas, apenas concatenando

### ISSUE THREAD

**Issue by Nykollas** [bielJS/gitsearch#3]
![image](https://user-images.githubusercontent.com/22648130/86691048-dc6d0a80-bfde-11ea-93a1-c44834dc87c5.png)

**Comment by bielJS** [comment]
Não é porque esta procurando a mesma org?

**Comment by Nykollas** [comment]
Ao usar orgs diferentes também concatena

**Comment by bielJS** [comment]
Você tem razão. Vou tentar corrigir isso depois. Obrigado.

**Comment by bielJS** [comment]
Mano, valeu pela ajuda.
